import uuid
from django.db import models
from django.conf import settings
from core.models.course_model import Course


class LTIRegistration(models.Model):
    """
    Stores a Moodle platform registration.
    Fill these in from the Moodle "View configuration details" dialog.
    """
    name = models.CharField(max_length=100, help_text="Friendly name, e.g. 'Local Moodle'")

    # Values you get FROM Moodle
    issuer = models.URLField(unique=True, help_text="Platform ID (issuer), e.g. http://localhost:8060")
    client_id = models.CharField(max_length=255, help_text="Client ID shown by Moodle")
    deployment_id = models.CharField(max_length=255)
    auth_request_url = models.URLField(help_text="Authentication request URL from Moodle")
    access_token_url = models.URLField(help_text="Access token URL from Moodle")
    platform_jwks_url = models.URLField(help_text="Moodle's public keyset URL")

    # RS256 key pair generated by us — store PEM strings
    # Generate once with: from cryptography.hazmat.primitives.asymmetric import rsa
    tool_private_key = models.TextField(help_text="RS256 private key PEM (generated by Erudite)")
    tool_public_key = models.TextField(help_text="RS256 public key PEM (generated by Erudite)")
    # A stable key ID for the JWKS endpoint
    tool_key_id = models.CharField(max_length=64, default=uuid.uuid4)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} ({self.issuer})"


class LTIResourceMapping(models.Model):
    """
    Maps a Moodle activity (resource_link_id) to an Erudite course.
    Created automatically on first launch, or manually by the teacher.
    """
    registration = models.ForeignKey(LTIRegistration, on_delete=models.CASCADE, related_name="mappings")
    resource_link_id = models.CharField(max_length=255, help_text="resource_link_id from the LTI launch claim")
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="lti_mappings", null=True, blank=True)

    # AGS (grade passback) endpoints sent in the launch JWT
    lineitem_url = models.URLField(blank=True, null=True, help_text="AGS lineitem URL for grade passback")

    class Meta:
        unique_together = ("registration", "resource_link_id")

    def __str__(self):
        return f"{self.resource_link_id} → {self.course.title}"


class LTISession(models.Model):
    """
    Tracks an active LTI user session.
    Created on successful launch, used to identify the student.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="lti_sessions")
    registration = models.ForeignKey(LTIRegistration, on_delete=models.CASCADE)
    resource_mapping = models.ForeignKey(LTIResourceMapping, on_delete=models.CASCADE)

    # The sub claim from the LTI JWT (platform's user identifier)
    lti_user_id = models.CharField(max_length=255)

    # AGS score URL (per-user grade URL if platform supports it)
    score_url = models.URLField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"LTISession({self.user.email}, {self.resource_mapping})"
