version: '3.10'

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql/data

  web:
    build: .
    command: >
      bash -c "./wait-for-it.sh db:5432 -- \
      python manage.py collectstatic --no-input && \
      python manage.py migrate && \
      python manage.py createsuperuser --no-input || true && \
      gunicorn config.wsgi:application -w 4 -b 0.0.0.0:8080"
    volumes:
      - .:/app
      - ./static:/app/static
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env