# Generated by Django 5.2.6 on 2026-03-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('graded', 'Graded'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
