# Generated by Django 5.2.6 on 2026-05-03 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_type',
            field=models.CharField(choices=[('quiz', 'Quiz (MCQ)'), ('text', 'Text answer'), ('code', 'Code')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='challenge',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='solution_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='completion_threshold',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='submission',
            name='hint_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='solution_revealed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('graded', 'Graded'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CodeChallengeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python 3'), ('javascript', 'JavaScript (Node)'), ('java', 'Java'), ('cpp', 'C++'), ('sql', 'SQL')], max_length=30)),
                ('solution_template', models.TextField(blank=True)),
                ('solution_hidden', models.TextField(blank=True)),
                ('time_limit_seconds', models.PositiveIntegerField(default=5)),
                ('memory_limit_mb', models.PositiveIntegerField(default=128)),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_config', to='core.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='CodeTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdin', models.TextField(blank=True)),
                ('expected_stdout', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('weight', models.FloatField(default=1.0)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='core.codechallengeconfig')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CodeSubmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit', 'Time Limit Exceeded'), ('memory_limit', 'Memory Limit Exceeded'), ('runtime_error', 'Runtime Error'), ('compilation_error', 'Compilation Error')], max_length=30)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('execution_time_ms', models.FloatField(null=True)),
                ('memory_used_mb', models.FloatField(null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='core.submission')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.codetestcase')),
            ],
        ),
    ]
