# Generated by Django 5.2.6 on 2026-03-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_completion_threshold_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='certificate',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
