# Generated by Django 5.2.6 on 2026-03-19 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_certificate_pdf_file_certificate_pdf_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='pdf_url',
        ),
    ]
