# Generated by Django 5.2.6 on 2026-03-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_certificate_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_photos/'),
        ),
    ]
