# Generated by Django 5.2.6 on 2026-03-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_challenge_hint_solution_submission_flags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lti_token',
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='lti_source',
            field=models.CharField(blank=True, help_text='LTI platform that created this enrollment, if any.', max_length=200, null=True),
        ),
    ]
