# Generated by Django 5.2.6 on 2026-03-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='moodle_platform',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
