# Generated by Django 5.2.6 on 2026-03-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_moodle_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='moodle_platform',
            field=models.CharField(blank=True, help_text='Moodle/LTI platform identifier. Set means username is managed externally.', max_length=200, null=True),
        ),
    ]
