# Generated by Django 5.2.6 on 2026-05-13 09:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LTIRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name, e.g. 'Local Moodle'", max_length=100)),
                ('issuer', models.URLField(help_text='Platform ID (issuer), e.g. http://localhost:8060', unique=True)),
                ('client_id', models.CharField(help_text='Client ID shown by Moodle', max_length=255)),
                ('deployment_id', models.CharField(max_length=255)),
                ('auth_request_url', models.URLField(help_text='Authentication request URL from Moodle')),
                ('access_token_url', models.URLField(help_text='Access token URL from Moodle')),
                ('platform_jwks_url', models.URLField(help_text="Moodle's public keyset URL")),
                ('tool_private_key', models.TextField(help_text='RS256 private key PEM (generated by Erudite)')),
                ('tool_public_key', models.TextField(help_text='RS256 public key PEM (generated by Erudite)')),
                ('tool_key_id', models.CharField(default=uuid.uuid4, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LTIResourceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_link_id', models.CharField(help_text='resource_link_id from the LTI launch claim', max_length=255)),
                ('lineitem_url', models.URLField(blank=True, help_text='AGS lineitem URL for grade passback', null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lti_mappings', to='core.course')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='lti.ltiregistration')),
            ],
            options={
                'unique_together': {('registration', 'resource_link_id')},
            },
        ),
        migrations.CreateModel(
            name='LTISession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lti_user_id', models.CharField(max_length=255)),
                ('score_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti.ltiregistration')),
                ('resource_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti.ltiresourcemapping')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lti_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
